INSERT INTO OWNERS(ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER) 
VALUES (1,'Hashem','Abandeh','07812');

INSERT INTO OWNERS(ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER) 
VALUES (2,'Foad','Abandeh','0792');

INSERT INTO PETS(ID, AGE, NAME, OWNER)
VALUES(1, 3, 'Rix1', 1);

INSERT INTO PETS(ID, AGE, NAME, OWNER)
VALUES(2,4, 'Rix2', 1);
