INSERT INTO OWNER(ID, FIRST_NAME, LAST_NAME, PHONE) 
VALUES (1,'Hashem','Abandeh','07812');

INSERT INTO OWNER(ID, FIRST_NAME, LAST_NAME, PHONE) 
VALUES (2,'Foad','Abandeh','0792');

INSERT INTO PET(ID, NAME, OWNER)
VALUES(1,'Rix1', 1);

INSERT INTO PET(ID, NAME, OWNER)
VALUES(2,'Rix2', 1);
